In [1]:
import pandas as pd

In [5]:
df = pd.read_csv("city_revenue_sales.csv")

In [6]:
df

    OrderID   OrderDate              Product Quantity  UnitPrice       City
0      4001  2026-04-01               Laptop        2     650.00    Chennai
1      4002  2026-04-02                Mouse        5      18.50    chennai
2      4003  2026-04-03              Monitor        2     180.00  Hyderabad
3      4004  2026-04-04             Keyboard        3      32.00  Bengaluru
4      4005  2026-04-05        Gaming Laptop        1    1450.00     Mumbai
5      4006  2026-04-06           Headphones      two      45.00       Pune
6      4007  2026-04-07         External SSD        1      89.99      Delhi
7      4008  2026-04-08              Printer        1     155.00    Chennai
8      4009  2026-04-09        Graphics Card        1     899.00  Hyderabad
9      4010  2026-04-10            USB Cable        5       7.99       Pune
10     4011  2026-04-11           Smartphone        1     799.00     Mumbai
11     4012  2026-04-12               Tablet        2     240.00      Delhi
12     4013  2026-04-13      Docking Station        1     120.00  Bengaluru
13     4014  2026-04-14               Webcam        3      39.99    Chennai
14     4015  2026-04-15            Projector        1    1250.00  hyderabad
15     4016  2026-04-16           Microphone        2      59.00       Pune
16     4017  2026-04-17           4K Monitor        1     499.00        NaN
17     4018  2026-04-18               Laptop        1     650.00      Delhi
18     4019  2026-04-19               Router        2        NaN     Mumbai
19     4020  2026-04-20  Mechanical Keyboard        2     129.00    Chennai
20     4021  2026-04-21               Camera        1     999.00  Bengaluru
21     4022  2026-04-22           Smartwatch        2     220.00  Hyderabad
22     4023  2026-04-23           Power Bank        4      22.00       Pune
23     4024  2026-04-24         Laptop Stand        2      27.50   chennai

In [7]:
df.head()

   OrderID   OrderDate        Product Quantity  UnitPrice       City
0     4001  2026-04-01         Laptop        2      650.0    Chennai
1     4002  2026-04-02          Mouse        5       18.5    chennai
2     4003  2026-04-03        Monitor        2      180.0  Hyderabad
3     4004  2026-04-04       Keyboard        3       32.0  Bengaluru
4     4005  2026-04-05  Gaming Laptop        1     1450.0     Mumbai

In [8]:
df.tail()

    OrderID   OrderDate              Product Quantity  UnitPrice       City
19     4020  2026-04-20  Mechanical Keyboard        2      129.0    Chennai
20     4021  2026-04-21               Camera        1      999.0  Bengaluru
21     4022  2026-04-22           Smartwatch        2      220.0  Hyderabad
22     4023  2026-04-23           Power Bank        4       22.0       Pune
23     4024  2026-04-24         Laptop Stand        2       27.5   chennai

In [9]:
df.columns

Index(['OrderID', 'OrderDate', 'Product', 'Quantity', 'UnitPrice', 'City'],
      dtype='str')

In [10]:
df.shape

(24, 6)

In [11]:
df.describe()

           OrderID    UnitPrice
count    24.000000    23.000000
mean   4012.500000   373.129130
std       7.071068   437.594703
min    4001.000000     7.990000
25%    4006.750000    42.495000
50%    4012.500000   155.000000
75%    4018.250000   650.000000
max    4024.000000  1450.000000

In [12]:
df.dtypes

OrderID        int64
OrderDate        str
Product          str
Quantity         str
UnitPrice    float64
City             str
dtype: object

In [13]:
df.isnull().sum()

OrderID      0
OrderDate    0
Product      0
Quantity     0
UnitPrice    1
City         1
dtype: int64

In [18]:
df.duplicated().sum()

np.int64(0)

In [21]:
#Standarized city names

df["City"] = df["City"].str.strip().str.title()

In [22]:
df["City"] = df["City"].fillna("Unknown")
df["City"]

0       Chennai
1       Chennai
2     Hyderabad
3     Bengaluru
4        Mumbai
5          Pune
6         Delhi
7       Chennai
8     Hyderabad
9          Pune
10       Mumbai
11        Delhi
12    Bengaluru
13      Chennai
14    Hyderabad
15         Pune
16      Unknown
17        Delhi
18       Mumbai
19      Chennai
20    Bengaluru
21    Hyderabad
22         Pune
23      Chennai
Name: City, dtype: str

In [23]:
df["Quantity"] = pd.to_numeric(df["Quantity"], errors="coerce")

In [24]:
df["UnitPrice"] = pd.to_numeric(df["UnitPrice"], errors="coerce")

In [25]:
df.isnull().sum()

OrderID      0
OrderDate    0
Product      0
Quantity     1
UnitPrice    1
City         0
dtype: int64

In [26]:
df["Revenue"] = df["Quantity"] * df["UnitPrice"]

In [27]:
df

,OrderID,OrderDate,Product,Quantity,UnitPrice,City,Revenue
0,4001,2026-04-01,Laptop,2.0,650.00,Chennai,1300.00
1,4002,2026-04-02,Mouse,5.0,18.50,Chennai,92.50
2,4003,2026-04-03,Monitor,2.0,180.00,Hyderabad,360.00
3,4004,2026-04-04,Keyboard,3.0,32.00,Bengaluru,96.00
4,4005,2026-04-05,Gaming Laptop,1.0,1450.00,Mumbai,1450.00
5,4006,2026-04-06,Headphones,NaN,45.00,Pune,NaN
6,4007,2026-04-07,External SSD,1.0,89.99,Delhi,89.99
7,4008,2026-04-08,Printer,1.0,155.00,Chennai,155.00
8,4009,2026-04-09,Graphics Card,1.0,899.00,Hyderabad,899.00
9,4010,2026-04-10,USB Cable,5.0,7.99,Pune,39.95
10,4011,2026-04-11,Smartphone,1.0,799.00,Mumbai,799.00
11,4012,2026-04-12,Tablet,2.0,240.00,Delhi,480.00
12,4013,2026-04-13,Docking Station,1.0,120.00,Bengaluru,120.00
13,4014,2026-04-14,Webcam,3.0,39.99,Chennai,119.97
14,4015,2026-04-15,Projector,1.0,1250.00,Hyderabad,1250.00
15,4016,2026-04-16,Microphone,2.0,59.00,Pune,118.00
16,4017,2026-04-17,4K Monitor,1.0,499.00,Unknown,499.00
17,4018,2026-04-18,Laptop,1.0,650.00,Delhi,650.00
18,4019,2026-04-19,Router,2.0,NaN,Mumbai,NaN
19,4020,2026-04-20,Mechanical Keyboard,2.0,129.00,Chennai,258.00
20,4021,2026-04-21,Camera,1.0,999.00,Bengaluru,999.00
21,4022,2026-04-22,Smartwatch,2.0,220.00,Hyderabad,440.00
22,4023,2026-04-23,Power Bank,4.0,22.00,Pune,88.00
23,4024,2026-04-24,Laptop Stand,2.0,27.50,Chennai,55.00

In [28]:
df[["City", "Quantity", "UnitPrice", "Revenue"]]

         City  Quantity  UnitPrice  Revenue
0     Chennai       2.0     650.00  1300.00
1     Chennai       5.0      18.50    92.50
2   Hyderabad       2.0     180.00   360.00
3   Bengaluru       3.0      32.00    96.00
4      Mumbai       1.0    1450.00  1450.00
5        Pune       NaN      45.00      NaN
6       Delhi       1.0      89.99    89.99
7     Chennai       1.0     155.00   155.00
8   Hyderabad       1.0     899.00   899.00
9        Pune       5.0       7.99    39.95
10     Mumbai       1.0     799.00   799.00
11      Delhi       2.0     240.00   480.00
12  Bengaluru       1.0     120.00   120.00
13    Chennai       3.0      39.99   119.97
14  Hyderabad       1.0    1250.00  1250.00
15       Pune       2.0      59.00   118.00
16    Unknown       1.0     499.00   499.00
17      Delhi       1.0     650.00   650.00
18     Mumbai       2.0        NaN      NaN
19    Chennai       2.0     129.00   258.00
20  Bengaluru       1.0     999.00   999.00
21  Hyderabad       2.0     220.00   440.00
22       Pune       4.0      22.00    88.00
23    Chennai       2.0      27.50    55.00

In [29]:
city_revenue = df.groupby("City")["Revenue"].sum()

In [32]:
city_revenue.sort_values(ascending=False)

city_revenue

City
Bengaluru    1215.00
Chennai      1980.47
Delhi        1219.99
Hyderabad    2949.00
Mumbai       2249.00
Pune          245.95
Unknown       499.00
Name: Revenue, dtype: float64

In [33]:
city_revenue.idxmax()

'Hyderabad'

In [34]:
df.to_csv("sales_revenue_analysis.csv", index=False)