In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("sales_inspection_day11.csv")

In [3]:
df

    OrderID   OrderDate              Product  Quantity  UnitPrice       City
0      3001  2026-03-01               Laptop         1     650.00    Chennai
1      3002  2026-03-02                Mouse         4      18.50    Chennai
2      3003  2026-03-03              Monitor         2     180.00  Hyderabad
3      3004  2026-03-04             Keyboard         3      32.00  Bengaluru
4      3005  2026-03-05        Gaming Laptop         1    1450.00     Mumbai
5      3006  2026-03-06           Headphones         2      45.00       Pune
6      3007  2026-03-07         External SSD         1      89.99      Delhi
7      3008  2026-03-08              Printer         1     155.00    Chennai
8      3009  2026-03-09        Graphics Card         1     899.00  Hyderabad
9      3010  2026-03-10            USB Cable         5       7.99       Pune
10     3011  2026-03-11           Smartphone         1     799.00     Mumbai
11     3012  2026-03-12               Tablet         2     240.00      Delhi
12     3013  2026-03-13      Docking Station         1     120.00  Bengaluru
13     3014  2026-03-14               Webcam         3      39.99    Chennai
14     3005  2026-03-05        Gaming Laptop         1    1450.00     Mumbai
15     3015  2026-03-15            Projector         1    1250.00  Hyderabad
16     3016  2026-03-16           Microphone         2      59.00       Pune
17     3017  2026-03-17           4K Monitor         1     499.00        NaN
18     3018  2026-03-18               Laptop         1     650.00      Delhi
19     3019  2026-03-19               Router         2        NaN     Mumbai
20     3020  2026-03-20  Mechanical Keyboard         2     129.00    Chennai
21     3021  2026-03-21               Camera         1     999.00  Bengaluru
22     3022  2026-03-22           Smartwatch         2     220.00  Hyderabad
23     3023  2026-03-23           Power Bank         4      22.00       Pune

In [4]:
df.head()

   OrderID   OrderDate        Product  Quantity  UnitPrice       City
0     3001  2026-03-01         Laptop         1      650.0    Chennai
1     3002  2026-03-02          Mouse         4       18.5    Chennai
2     3003  2026-03-03        Monitor         2      180.0  Hyderabad
3     3004  2026-03-04       Keyboard         3       32.0  Bengaluru
4     3005  2026-03-05  Gaming Laptop         1     1450.0     Mumbai

In [5]:
df.tail()

    OrderID   OrderDate              Product  Quantity  UnitPrice       City
19     3019  2026-03-19               Router         2        NaN     Mumbai
20     3020  2026-03-20  Mechanical Keyboard         2      129.0    Chennai
21     3021  2026-03-21               Camera         1      999.0  Bengaluru
22     3022  2026-03-22           Smartwatch         2      220.0  Hyderabad
23     3023  2026-03-23           Power Bank         4       22.0       Pune

In [6]:
df.shape

(24, 6)

In [7]:
df.columns

Index(['OrderID', 'OrderDate', 'Product', 'Quantity', 'UnitPrice', 'City'],
      dtype='str')

In [8]:
df.describe()

           OrderID   Quantity    UnitPrice
count    24.000000  24.000000    23.000000
mean   3011.708333   1.875000   434.976957
std       6.785401   1.153916   484.532276
min    3001.000000   1.000000     7.990000
25%    3005.750000   1.000000    52.000000
50%    3011.500000   1.500000   180.000000
75%    3017.250000   2.000000   724.500000
max    3023.000000   5.000000  1450.000000

In [9]:
df.describe(include = "all")

            OrderID   OrderDate Product   Quantity    UnitPrice     City
count     24.000000          24      24  24.000000    23.000000       23
unique          NaN          23      22        NaN          NaN        6
top             NaN  2026-03-05  Laptop        NaN          NaN  Chennai
freq            NaN           2       2        NaN          NaN        5
mean    3011.708333         NaN     NaN   1.875000   434.976957      NaN
std        6.785401         NaN     NaN   1.153916   484.532276      NaN
min     3001.000000         NaN     NaN   1.000000     7.990000      NaN
25%     3005.750000         NaN     NaN   1.000000    52.000000      NaN
50%     3011.500000         NaN     NaN   1.500000   180.000000      NaN
75%     3017.250000         NaN     NaN   2.000000   724.500000      NaN
max     3023.000000         NaN     NaN   5.000000  1450.000000      NaN

In [10]:
df.duplicated().sum()

np.int64(1)

In [11]:
df[df.duplicated()]

    OrderID   OrderDate        Product  Quantity  UnitPrice    City
14     3005  2026-03-05  Gaming Laptop         1     1450.0  Mumbai

In [12]:
df["OrderID"].duplicated().sum()

np.int64(1)

In [13]:
df[df["OrderID"].duplicated(keep=False)]

    OrderID   OrderDate        Product  Quantity  UnitPrice    City
4      3005  2026-03-05  Gaming Laptop         1     1450.0  Mumbai
14     3005  2026-03-05  Gaming Laptop         1     1450.0  Mumbai

In [15]:
#Convert unti-price into numeric

df["UnitPrice"] = pd.to_numeric(df["UnitPrice"], errors="coerce")
df["UnitPrice"]

0      650.00
1       18.50
2      180.00
3       32.00
4     1450.00
5       45.00
6       89.99
7      155.00
8      899.00
9        7.99
10     799.00
11     240.00
12     120.00
13      39.99
14    1450.00
15    1250.00
16      59.00
17     499.00
18     650.00
19        NaN
20     129.00
21     999.00
22     220.00
23      22.00
Name: UnitPrice, dtype: float64

In [16]:
# 5-highest priced product

df.nlargest(5, "UnitPrice")[["Product", "UnitPrice"]]

          Product  UnitPrice
4   Gaming Laptop     1450.0
14  Gaming Laptop     1450.0
15      Projector     1250.0
21         Camera      999.0
8   Graphics Card      899.0

In [17]:
df["UnitPrice"].max()

np.float64(1450.0)

In [18]:
df["UnitPrice"].min()

np.float64(7.99)