In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("sales_dirty.csv")

In [3]:
df.head()

   OrderID   OrderDate    Product  Quantity  UnitPrice
0     1001  2026-01-02     Laptop       2.0     650.00
1     1002  2026-01-03      Mouse       5.0      18.50
2     1003  2026-01-04   Keyboard       NaN      32.00
3     1004  2026-01-05    Monitor       1.0     180.00
4     1005  2026-01-06  USB Cable       4.0       7.99

In [4]:
df.tail()

    OrderID   OrderDate      Product  Quantity  UnitPrice
19     1020  2026-01-21       Router       1.0       64.0
20     1021  2026-01-22   Smartwatch       2.0      110.0
21     1022  2026-01-23  Flash Drive       8.0       12.5
22     1023  2026-01-24    Desk Lamp       3.0       26.0
23     1024  2026-01-25  Cooling Pad       NaN       31.0

In [5]:
df.columns

Index(['OrderID', 'OrderDate', 'Product', 'Quantity', 'UnitPrice'], dtype='str')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   OrderID    24 non-null     int64
 1   OrderDate  24 non-null     str
 2   Product    24 non-null     str
 3   Quantity   20 non-null     float64
 4   UnitPrice  24 non-null     float64
dtypes: float64(2), int64(1), str(2)
memory usage: 1.1 KB

In [7]:
df.shape

(24, 5)

In [8]:
df.describe()

           OrderID   Quantity   UnitPrice
count    24.000000  20.000000   24.000000
mean   1012.500000   2.750000   87.081667
std       7.071068   1.860249  134.030950
min    1001.000000   1.000000    7.990000
25%    1006.750000   1.750000   21.125000
50%    1012.500000   2.000000   42.495000
75%    1018.250000   3.250000   94.992500
max    1024.000000   8.000000  650.000000

In [9]:
df.isnull()

    OrderID  OrderDate  Product  Quantity  UnitPrice
0     False      False    False     False      False
1     False      False    False     False      False
2     False      False    False      True      False
3     False      False    False     False      False
4     False      False    False     False      False
5     False      False    False     False      False
6     False      False    False     False      False
7     False      False    False     False      False
8     False      False    False     False      False
9     False      False    False     False      False
10    False      False    False     False      False
11    False      False    False     False      False
12    False      False    False      True      False
13    False      False    False     False      False
14    False      False    False     False      False
15    False      False    False     False      False
16    False      False    False     False      False
17    False      False    False     False      False
18    False      False    False      True      False
19    False      False    False     False      False
20    False      False    False     False      False
21    False      False    False     False      False
22    False      False    False     False      False
23    False      False    False      True      False

In [10]:
df.isnull().sum()

OrderID      0
OrderDate    0
Product      0
Quantity     4
UnitPrice    0
dtype: int64

In [12]:
df.head(5).isna()

   OrderID  OrderDate  Product  Quantity  UnitPrice
0    False      False    False     False      False
1    False      False    False     False      False
2    False      False    False      True      False
3    False      False    False     False      False
4    False      False    False     False      False

In [13]:
#removing rows containing null values

In [14]:
df_cleaned = df.head(5).dropna()

df_cleaned

   OrderID   OrderDate    Product  Quantity  UnitPrice
0     1001  2026-01-02     Laptop       2.0     650.00
1     1002  2026-01-03      Mouse       5.0      18.50
3     1004  2026-01-05    Monitor       1.0     180.00
4     1005  2026-01-06  USB Cable       4.0       7.99

In [15]:
#calucalating the median of unti-price

df.head(5)["UnitPrice"].median()

np.float64(32.0)

In [17]:
#mean of unit-price

df.head(5)["UnitPrice"].mean()

np.float64(177.698)

In [18]:
#Filling Unit-price missing values with median

df["UnitPrice"] = df["UnitPrice"].fillna(df["UnitPrice"].median())

In [19]:
df["UnitPrice"]

0     650.00
1      18.50
2      32.00
3     180.00
4       7.99
5      45.00
6      39.99
7      27.50
8       9.50
9     120.00
10     59.00
11    240.00
12     15.00
13     89.99
14    155.00
15     11.99
16     48.00
17     22.00
18     75.00
19     64.00
20    110.00
21     12.50
22     26.00
23     31.00
Name: UnitPrice, dtype: float64

In [20]:
df

    OrderID   OrderDate          Product  Quantity  UnitPrice
0      1001  2026-01-02           Laptop       2.0     650.00
1      1002  2026-01-03            Mouse       5.0      18.50
2      1003  2026-01-04         Keyboard       NaN      32.00
3      1004  2026-01-05          Monitor       1.0     180.00
4      1005  2026-01-06        USB Cable       4.0       7.99
5      1006  2026-01-07       Headphones       2.0      45.00
6      1007  2026-01-08           Webcam       3.0      39.99
7      1008  2026-01-09     Laptop Stand       2.0      27.50
8      1009  2026-01-10        Mouse Pad       6.0       9.50
9      1010  2026-01-11  Docking Station       1.0     120.00
10     1011  2026-01-12       Microphone       2.0      59.00
11     1012  2026-01-13           Tablet       1.0     240.00
12     1013  2026-01-14          Charger       NaN      15.00
13     1014  2026-01-15     External SSD       2.0      89.99
14     1015  2026-01-16          Printer       1.0     155.00
15     1016  2026-01-17       HDMI Cable       3.0      11.99
16     1017  2026-01-18         Speakers       2.0      48.00
17     1018  2026-01-19       Power Bank       4.0      22.00
18     1019  2026-01-20  Graphics Tablet       NaN      75.00
19     1020  2026-01-21           Router       1.0      64.00
20     1021  2026-01-22       Smartwatch       2.0     110.00
21     1022  2026-01-23      Flash Drive       8.0      12.50
22     1023  2026-01-24        Desk Lamp       3.0      26.00
23     1024  2026-01-25      Cooling Pad       NaN      31.00

In [23]:
#converting Quantity into numeric values

df["Quantity"] = pd.to_numeric(df["Quantity"], errors="coerce")

In [24]:
df["Quantity"]

0     2.0
1     5.0
2     NaN
3     1.0
4     4.0
5     2.0
6     3.0
7     2.0
8     6.0
9     1.0
10    2.0
11    1.0
12    NaN
13    2.0
14    1.0
15    3.0
16    2.0
17    4.0
18    NaN
19    1.0
20    2.0
21    8.0
22    3.0
23    NaN
Name: Quantity, dtype: float64

In [26]:
df["Quantity"] = df["Quantity"].fillna(df["Quantity"].median())

In [27]:
df["Quantity"]

0     2.0
1     5.0
2     2.0
3     1.0
4     4.0
5     2.0
6     3.0
7     2.0
8     6.0
9     1.0
10    2.0
11    1.0
12    2.0
13    2.0
14    1.0
15    3.0
16    2.0
17    4.0
18    2.0
19    1.0
20    2.0
21    8.0
22    3.0
23    2.0
Name: Quantity, dtype: float64

In [28]:
df

    OrderID   OrderDate          Product  Quantity  UnitPrice
0      1001  2026-01-02           Laptop       2.0     650.00
1      1002  2026-01-03            Mouse       5.0      18.50
2      1003  2026-01-04         Keyboard       2.0      32.00
3      1004  2026-01-05          Monitor       1.0     180.00
4      1005  2026-01-06        USB Cable       4.0       7.99
5      1006  2026-01-07       Headphones       2.0      45.00
6      1007  2026-01-08           Webcam       3.0      39.99
7      1008  2026-01-09     Laptop Stand       2.0      27.50
8      1009  2026-01-10        Mouse Pad       6.0       9.50
9      1010  2026-01-11  Docking Station       1.0     120.00
10     1011  2026-01-12       Microphone       2.0      59.00
11     1012  2026-01-13           Tablet       1.0     240.00
12     1013  2026-01-14          Charger       2.0      15.00
13     1014  2026-01-15     External SSD       2.0      89.99
14     1015  2026-01-16          Printer       1.0     155.00
15     1016  2026-01-17       HDMI Cable       3.0      11.99
16     1017  2026-01-18         Speakers       2.0      48.00
17     1018  2026-01-19       Power Bank       4.0      22.00
18     1019  2026-01-20  Graphics Tablet       2.0      75.00
19     1020  2026-01-21           Router       1.0      64.00
20     1021  2026-01-22       Smartwatch       2.0     110.00
21     1022  2026-01-23      Flash Drive       8.0      12.50
22     1023  2026-01-24        Desk Lamp       3.0      26.00
23     1024  2026-01-25      Cooling Pad       2.0      31.00

In [29]:
df.head(5)

   OrderID   OrderDate    Product  Quantity  UnitPrice
0     1001  2026-01-02     Laptop       2.0     650.00
1     1002  2026-01-03      Mouse       5.0      18.50
2     1003  2026-01-04   Keyboard       2.0      32.00
3     1004  2026-01-05    Monitor       1.0     180.00
4     1005  2026-01-06  USB Cable       4.0       7.99