In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("sales_dirty_day11.csv")

In [3]:
df

    OrderID   OrderDate          Product Quantity  UnitPrice         City
0      2001  2026-02-01          Laptop         2     650.00      Chennai
1      2002  02/02/2026            mouse        5      18.50      chennai
2      2003  2026-02-03         KEYBOARD      two      32.00      CHENNAI
3      2004  2026-02-04          Monitor        1     180.00          NaN
4      2005  not-a-date       USB Cable         4       7.99   Hyderabad
5      2006  2026-02-06       Headphones      NaN      45.00    Bengaluru
6      2007  2026-02-07           webcam        3      39.99    hyderabad
7      2008  2026-02-08     Laptop Stand        2      27.50      Chennai
8      2009  2026-02-09        Mouse Pad        6       9.50         PUNE
9      2010  2026-02-10  Docking Station        1     120.00         Pune
10     2011  2026-02-11       Microphone        2      59.00       Mumbai
11     2012  2026-02-12           Tablet        1     240.00       mumbai
12     2013  2026-02-13          Charger        3      15.00          NaN
13     2014  2026-02-14     External SSD        2   99999.00        Delhi
14     2001  2026-02-01          Laptop         2     650.00      Chennai

In [4]:
df.head()

   OrderID   OrderDate      Product Quantity  UnitPrice         City
0     2001  2026-02-01      Laptop         2     650.00      Chennai
1     2002  02/02/2026        mouse        5      18.50      chennai
2     2003  2026-02-03     KEYBOARD      two      32.00      CHENNAI
3     2004  2026-02-04      Monitor        1     180.00          NaN
4     2005  not-a-date   USB Cable         4       7.99   Hyderabad

In [5]:
df.tail()

    OrderID   OrderDate       Product Quantity  UnitPrice     City
10     2011  2026-02-11    Microphone        2       59.0   Mumbai
11     2012  2026-02-12        Tablet        1      240.0   mumbai
12     2013  2026-02-13       Charger        3       15.0      NaN
13     2014  2026-02-14  External SSD        2    99999.0    Delhi
14     2001  2026-02-01       Laptop         2      650.0  Chennai

In [6]:
df.columns

Index(['OrderID', 'OrderDate', 'Product', 'Quantity', 'UnitPrice', 'City'],
      dtype='str')

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   OrderID    15 non-null     int64
 1   OrderDate  15 non-null     str
 2   Product    15 non-null     str
 3   Quantity   14 non-null     str
 4   UnitPrice  15 non-null     float64
 5   City       13 non-null     str
dtypes: float64(1), int64(1), str(4)
memory usage: 852.0 bytes

In [8]:
df.shape

(15, 6)

In [9]:
df.describe()

           OrderID     UnitPrice
count    15.000000     15.000000
mean   2007.066667   6806.232000
std       4.366539  25781.897161
min    2001.000000      7.990000
25%    2003.500000     23.000000
50%    2007.000000     45.000000
75%    2010.500000    210.000000
max    2014.000000  99999.000000

In [11]:
df.describe(include="all")

            OrderID   OrderDate   Product Quantity     UnitPrice     City
count     15.000000          15        15       14     15.000000       13
unique          NaN          14        14        7           NaN       11
top             NaN  2026-02-01   Laptop         2           NaN  Chennai
freq            NaN           2         2        5           NaN        3
mean    2007.066667         NaN       NaN      NaN   6806.232000      NaN
std        4.366539         NaN       NaN      NaN  25781.897161      NaN
min     2001.000000         NaN       NaN      NaN      7.990000      NaN
25%     2003.500000         NaN       NaN      NaN     23.000000      NaN
50%     2007.000000         NaN       NaN      NaN     45.000000      NaN
75%     2010.500000         NaN       NaN      NaN    210.000000      NaN
max     2014.000000         NaN       NaN      NaN  99999.000000      NaN

In [12]:
df.isnull()

    OrderID  OrderDate  Product  Quantity  UnitPrice   City
0     False      False    False     False      False  False
1     False      False    False     False      False  False
2     False      False    False     False      False  False
3     False      False    False     False      False   True
4     False      False    False     False      False  False
5     False      False    False      True      False  False
6     False      False    False     False      False  False
7     False      False    False     False      False  False
8     False      False    False     False      False  False
9     False      False    False     False      False  False
10    False      False    False     False      False  False
11    False      False    False     False      False  False
12    False      False    False     False      False   True
13    False      False    False     False      False  False
14    False      False    False     False      False  False

In [13]:
df.isnull().sum()

OrderID      0
OrderDate    0
Product      0
Quantity     1
UnitPrice    0
City         2
dtype: int64

In [14]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14     True
dtype: bool

In [15]:
df.duplicated().sum()

np.int64(1)

In [17]:
#remove duplicated data

df = df.drop_duplicates()

In [18]:
df.duplicated().sum()

np.int64(0)

In [19]:
#Standarizing

df["Product"] = df["Product"].str.strip().str.title()

In [20]:
df["Product"].head()

0       Laptop
1        Mouse
2     Keyboard
3      Monitor
4    Usb Cable
Name: Product, dtype: str

In [21]:
df["City"] = df["City"].str.strip().str.title()

In [22]:
df["City"].head()

0      Chennai
1      Chennai
2      Chennai
3          NaN
4    Hyderabad
Name: City, dtype: str

In [23]:
df["OrderDate"] = pd.to_datetime(df["OrderDate"], errors="coerce")

In [24]:
df["OrderDate"].head()

0   2026-02-01
1          NaT
2   2026-02-03
3   2026-02-04
4          NaT
Name: OrderDate, dtype: datetime64[us]

In [25]:
#Convert Quantity into numeric format

df["Quantity"] = pd.to_numeric(df["Quantity"], errors="coerce")

In [26]:
df["Quantity"].head()

0    2.0
1    5.0
2    NaN
3    1.0
4    4.0
Name: Quantity, dtype: float64

In [27]:
df["UnitPrice"] = pd.to_numeric(df["UnitPrice"], errors="coerce")

In [29]:
df["UnitPrice"].head()

0    650.00
1     18.50
2     32.00
3    180.00
4      7.99
Name: UnitPrice, dtype: float64

In [30]:
#meadin Quantity

df["Quantity"].median()

np.float64(2.0)

In [33]:
df["Quantity"] = df["Quantity"].fillna(df["Quantity"].median())
df["Quantity"]

0     2.0
1     5.0
2     2.0
3     1.0
4     4.0
5     2.0
6     3.0
7     2.0
8     6.0
9     1.0
10    2.0
11    1.0
12    3.0
13    2.0
Name: Quantity, dtype: float64

In [32]:
df["UnitPrice"].median()

np.float64(42.495000000000005)

In [34]:
df["UnitPrice"] = df["UnitPrice"].fillna(df["UnitPrice"].median())

df["UnitPrice"]

0       650.00
1        18.50
2        32.00
3       180.00
4         7.99
5        45.00
6        39.99
7        27.50
8         9.50
9       120.00
10       59.00
11      240.00
12       15.00
13    99999.00
Name: UnitPrice, dtype: float64

In [35]:
#Filling missing cities
df["City"] = df["City"].fillna("Unknown")

In [36]:
df["City"]

0       Chennai
1       Chennai
2       Chennai
3       Unknown
4     Hyderabad
5     Bengaluru
6     Hyderabad
7       Chennai
8          Pune
9          Pune
10       Mumbai
11       Mumbai
12      Unknown
13        Delhi
Name: City, dtype: str

In [37]:
def categorize_price(price):
    if pd.isna(price):
        return "Unknown"
    elif price < 50:
        return "Low"
    elif price < 200:
        return "Medium"
    else:
        return "High"

In [38]:
df["PriceCategory"] = df["UnitPrice"].apply(categorize_price)

In [39]:
df["PriceCategory"]

0       High
1        Low
2        Low
3     Medium
4        Low
5        Low
6        Low
7        Low
8        Low
9     Medium
10    Medium
11      High
12       Low
13      High
Name: PriceCategory, dtype: str

In [40]:
df

,OrderID,OrderDate,Product,Quantity,UnitPrice,City,PriceCategory
0,2001,2026-02-01,Laptop,2.0,650.00,Chennai,High
1,2002,NaT,Mouse,5.0,18.50,Chennai,Low
2,2003,2026-02-03,Keyboard,2.0,32.00,Chennai,Low
3,2004,2026-02-04,Monitor,1.0,180.00,Unknown,Medium
4,2005,NaT,Usb Cable,4.0,7.99,Hyderabad,Low
5,2006,2026-02-06,Headphones,2.0,45.00,Bengaluru,Low
6,2007,2026-02-07,Webcam,3.0,39.99,Hyderabad,Low
7,2008,2026-02-08,Laptop Stand,2.0,27.50,Chennai,Low
8,2009,2026-02-09,Mouse Pad,6.0,9.50,Pune,Low
9,2010,2026-02-10,Docking Station,1.0,120.00,Pune,Medium
10,2011,2026-02-11,Microphone,2.0,59.00,Mumbai,Medium
11,2012,2026-02-12,Tablet,1.0,240.00,Mumbai,High
12,2013,2026-02-13,Charger,3.0,15.00,Unknown,Low
13,2014,2026-02-14,External Ssd,2.0,99999.00,Delhi,High

In [41]:
df["Revenue"] = df["Quantity"] * df["UnitPrice"]

In [42]:
df

,OrderID,OrderDate,Product,Quantity,UnitPrice,City,PriceCategory,Revenue
0,2001,2026-02-01,Laptop,2.0,650.00,Chennai,High,1300.00
1,2002,NaT,Mouse,5.0,18.50,Chennai,Low,92.50
2,2003,2026-02-03,Keyboard,2.0,32.00,Chennai,Low,64.00
3,2004,2026-02-04,Monitor,1.0,180.00,Unknown,Medium,180.00
4,2005,NaT,Usb Cable,4.0,7.99,Hyderabad,Low,31.96
5,2006,2026-02-06,Headphones,2.0,45.00,Bengaluru,Low,90.00
6,2007,2026-02-07,Webcam,3.0,39.99,Hyderabad,Low,119.97
7,2008,2026-02-08,Laptop Stand,2.0,27.50,Chennai,Low,55.00
8,2009,2026-02-09,Mouse Pad,6.0,9.50,Pune,Low,57.00
9,2010,2026-02-10,Docking Station,1.0,120.00,Pune,Medium,120.00
10,2011,2026-02-11,Microphone,2.0,59.00,Mumbai,Medium,118.00
11,2012,2026-02-12,Tablet,1.0,240.00,Mumbai,High,240.00
12,2013,2026-02-13,Charger,3.0,15.00,Unknown,Low,45.00
13,2014,2026-02-14,External Ssd,2.0,99999.00,Delhi,High,199998.00

In [43]:
df.isnull().sum()

OrderID          0
OrderDate        2
Product          0
Quantity         0
UnitPrice        0
City             0
PriceCategory    0
Revenue          0
dtype: int64

In [44]:
df.dtypes

OrderID                   int64
OrderDate        datetime64[us]
Product                     str
Quantity                float64
UnitPrice               float64
City                        str
PriceCategory               str
Revenue                 float64
dtype: object

In [45]:
df.to_csv("sales_cleaned.csv", index=False)