In [1]:
import numpy as np
import pandas as pd

In [2]:
marks = np.array([75, 80, 90, 65, 85])

In [3]:
print("Array:", marks)

Array: [75 80 90 65 85]

In [4]:
print("Total elements:", marks.size)

Total elements: 5

In [5]:
print("Sum:", np.sum(marks))

Sum: 395

In [6]:
print("Average:", np.average(marks))

Average: 79.0

In [7]:
print("Mean:", np.mean(marks))

Mean: 79.0

In [8]:
print("Minimum:", np.min(marks))

Minimum: 65

In [9]:
print("Maximum:", np.max(marks))

Maximum: 90

In [11]:
print("Standard Deviation:", np.std(marks))

Standard Deviation: 8.602325267042627

In [12]:
print("Median:", np.median(marks))

Median: 80.0

In [13]:
print("Sorted Array:", np.sort(marks))

Sorted Array: [65 75 80 85 90]

In [14]:
print("All marks greater than 60:", np.all(marks > 60))

All marks greater than 60: True

In [16]:
print("Any marks greater than 85:", np.any(marks > 85))

Any marks greater than 85: True

In [17]:
data = {
    "Name": ["Anu", "Bala", "Charan", "Divya", "Esha", "Farhan"],
    "Department": ["CSE", "ECE", "CSE", "IT", "ECE", "IT"],
    "Marks": [85, 72, 90, 65, 78, 88],
    "Attendance": [95, 80, 92, 70, 85, 90]
}

df = pd.DataFrame(data)

print(df)

     Name Department  Marks  Attendance
0     Anu        CSE     85          95
1    Bala        ECE     72          80
2  Charan        CSE     90          92
3   Divya         IT     65          70
4    Esha        ECE     78          85
5  Farhan         IT     88          90

In [18]:
print(df.isnull().sum())

Name          0
Department    0
Marks         0
Attendance    0
dtype: int64

In [19]:
print(df.duplicated())

0    False
1    False
2    False
3    False
4    False
5    False
dtype: bool

In [20]:

print(df.duplicated().sum())

0

In [21]:
print(df.columns)

Index(['Name', 'Department', 'Marks', 'Attendance'], dtype='str')

In [23]:
print(df.dtypes)

Name            str
Department      str
Marks         int64
Attendance    int64
dtype: object

In [24]:
df.shape

(6, 4)

In [26]:
df.columns.tolist()

['Name', 'Department', 'Marks', 'Attendance']

In [33]:
df.head()

     Name Department  Marks  Attendance
0     Anu        CSE     85          95
1    Bala        ECE     72          80
2  Charan        CSE     90          92
3   Divya         IT     65          70
4    Esha        ECE     78          85

In [32]:
df.tail()

     Name Department  Marks  Attendance
1    Bala        ECE     72          80
2  Charan        CSE     90          92
3   Divya         IT     65          70
4    Esha        ECE     78          85
5  Farhan         IT     88          90

In [29]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      str
 1   Department  6 non-null      str
 2   Marks       6 non-null      int64
 3   Attendance  6 non-null      int64
dtypes: int64(2), str(2)
memory usage: 324.0 bytes

In [31]:
df.describe()

           Marks  Attendance
count   6.000000    6.000000
mean   79.666667   85.333333
std     9.811558    9.201449
min    65.000000   70.000000
25%    73.500000   81.250000
50%    81.500000   87.500000
75%    87.250000   91.500000
max    90.000000   95.000000

In [34]:
df["Final_Score"] = (
    df["Marks"] * 0.8 +
    df["Attendance"] * 0.2
)

print(df)

     Name Department  Marks  Attendance  Final_Score
0     Anu        CSE     85          95         87.0
1    Bala        ECE     72          80         73.6
2  Charan        CSE     90          92         90.4
3   Divya         IT     65          70         66.0
4    Esha        ECE     78          85         79.4
5  Farhan         IT     88          90         88.4

In [35]:
df.head()

     Name Department  Marks  Attendance  Final_Score
0     Anu        CSE     85          95         87.0
1    Bala        ECE     72          80         73.6
2  Charan        CSE     90          92         90.4
3   Divya         IT     65          70         66.0
4    Esha        ECE     78          85         79.4

In [37]:
print(df["Marks"].sum())

478

In [38]:
print("Marks Mean:", df["Marks"].mean())

Marks Mean: 79.66666666666667

In [39]:
print("Marks Median:", df["Marks"].median())

Marks Median: 81.5

In [40]:
print("Marks Standard Deviation:", df["Marks"].std())

Marks Standard Deviation: 9.811557810392124

In [41]:
print("Marks Minimum:", df["Marks"].min())

Marks Minimum: 65

In [42]:
print("Marks Maximum:", df["Marks"].max())

Marks Maximum: 90

In [43]:
print("Marks Count:", df["Marks"].count())

Marks Count: 6

In [45]:
print("Attendance Sum:", df["Attendance"].sum())

Attendance Sum: 512

In [46]:
print("Attendance Mean:", df["Attendance"].mean())

Attendance Mean: 85.33333333333333

In [47]:
print("Attendance Median:", df["Attendance"].median())

Attendance Median: 87.5

In [48]:
print("Attendance Standard Deviation:", df["Attendance"].std())

Attendance Standard Deviation: 9.201449161228174

In [49]:
print("Attendance Minimum:", df["Attendance"].min())
print("Attendance Maximum:", df["Attendance"].max())

Attendance Minimum: 70
Attendance Maximum: 95

In [50]:
print("Final Score Sum:", df["Final_Score"].sum())
print("Final Score Mean:", df["Final_Score"].mean())
print("Final Score Median:", df["Final_Score"].median())
print("Final Score Standard Deviation:", df["Final_Score"].std())
print("Final Score Minimum:", df["Final_Score"].min())
print("Final Score Maximum:", df["Final_Score"].max())

Final Score Sum: 484.79999999999995
Final Score Mean: 80.8
Final Score Median: 83.2
Final Score Standard Deviation: 9.604165762834379
Final Score Minimum: 66.0
Final Score Maximum: 90.4

In [51]:
print(df[["Marks", "Attendance", "Final_Score"]].agg([
    "sum",
    "mean",
    "median",
    "std",
    "min",
    "max"
]))

             Marks  Attendance  Final_Score
sum     478.000000  512.000000   484.800000
mean     79.666667   85.333333    80.800000
median   81.500000   87.500000    83.200000
std       9.811558    9.201449     9.604166
min      65.000000   70.000000    66.000000
max      90.000000   95.000000    90.400000

In [52]:
print(df[df["Marks"] > 80])

     Name Department  Marks  Attendance  Final_Score
0     Anu        CSE     85          95         87.0
2  Charan        CSE     90          92         90.4
5  Farhan         IT     88          90         88.4

In [53]:
print(df[df["Attendance"] > 85])

     Name Department  Marks  Attendance  Final_Score
0     Anu        CSE     85          95         87.0
2  Charan        CSE     90          92         90.4
5  Farhan         IT     88          90         88.4

In [54]:
print(df[df["Department"] == "CSE"])

     Name Department  Marks  Attendance  Final_Score
0     Anu        CSE     85          95         87.0
2  Charan        CSE     90          92         90.4

In [56]:
print(df[(df["Marks"] > 80) & (df["Attendance"] > 90)])

     Name Department  Marks  Attendance  Final_Score
0     Anu        CSE     85          95         87.0
2  Charan        CSE     90          92         90.4

In [57]:
print(df[(df["Marks"] < 80) | (df["Attendance"] < 80)])

    Name Department  Marks  Attendance  Final_Score
1   Bala        ECE     72          80         73.6
3  Divya         IT     65          70         66.0
4   Esha        ECE     78          85         79.4

In [58]:
print(df[df["Marks"].between(70, 90)])

     Name Department  Marks  Attendance  Final_Score
0     Anu        CSE     85          95         87.0
1    Bala        ECE     72          80         73.6
2  Charan        CSE     90          92         90.4
4    Esha        ECE     78          85         79.4
5  Farhan         IT     88          90         88.4

In [61]:
print(df[df["Department"].isin(["CSE", "IT"])])

     Name Department  Marks  Attendance  Final_Score
0     Anu        CSE     85          95         87.0
2  Charan        CSE     90          92         90.4
3   Divya         IT     65          70         66.0
5  Farhan         IT     88          90         88.4

In [62]:
print(df[["Name", "Marks", "Final_Score"]])

     Name  Marks  Final_Score
0     Anu     85         87.0
1    Bala     72         73.6
2  Charan     90         90.4
3   Divya     65         66.0
4    Esha     78         79.4
5  Farhan     88         88.4

In [63]:
print(df.sort_values(by="Marks", ascending=False))

     Name Department  Marks  Attendance  Final_Score
2  Charan        CSE     90          92         90.4
5  Farhan         IT     88          90         88.4
0     Anu        CSE     85          95         87.0
4    Esha        ECE     78          85         79.4
1    Bala        ECE     72          80         73.6
3   Divya         IT     65          70         66.0

In [64]:
print(df[df["Marks"] == df["Marks"].max()])

     Name Department  Marks  Attendance  Final_Score
2  Charan        CSE     90          92         90.4

In [66]:
df.isnull().sum()

Name           0
Department     0
Marks          0
Attendance     0
Final_Score    0
dtype: int64

In [67]:
df[df["Marks"] > 80]

     Name Department  Marks  Attendance  Final_Score
0     Anu        CSE     85          95         87.0
2  Charan        CSE     90          92         90.4
5  Farhan         IT     88          90         88.4

In [68]:
df[df["Attendance"] > 85]

     Name Department  Marks  Attendance  Final_Score
0     Anu        CSE     85          95         87.0
2  Charan        CSE     90          92         90.4
5  Farhan         IT     88          90         88.4

In [69]:
df[df["Department"] == "CSE"]

     Name Department  Marks  Attendance  Final_Score
0     Anu        CSE     85          95         87.0
2  Charan        CSE     90          92         90.4

In [70]:
df[(df["Marks"] > 80) & (df["Attendance"] > 90)]

     Name Department  Marks  Attendance  Final_Score
0     Anu        CSE     85          95         87.0
2  Charan        CSE     90          92         90.4